SELECT * FROM MEMBER;
DELETE FROM MEMBER;
INSERT INTO MEMBER (USERID, ENROLL_DATE, PASSWORD, PHONE)
	values('admin', sysdate, '$2a$10$8Ub3qWBM7/BSZHrC/GnOS.6LgoyGXsNDImCD0sbRN.3PNKRCGzfg.', '01012341234');
	

SELECT * FROM MEMBER;