server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@61.78.121.242:8877:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: cucumber
    password: cucumber123
    
    #connection pool설정
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: cupool
#파일 업로드 처리  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
        
        
#mvc패턴으로 jsp페이지 연결하기
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
        
#jpa환경설정하기
  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle9iDialect
    hibernate: 
      ddl-auto: update
      use-new-id-generator-mappings: true
      

    properties:
      hibernate:
        format_sql: true  


#    properties:
#      hibernate:
#        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: shinedakth@gmail.com
    password: ekancbdildjukhru
    properties:
      mail:
        smtp:
          transport:
            protocol: smtp
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            trust: stmp.gmail.com
            protocols: TLSv1.2
        debug: true
        

logging:
  level:
    root: info
    '[org.hibernate.type.descriptor.sql]': trace
    com.cu.cum: debug



   
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml


