server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@61.78.121.242:8877:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: cucumber
    password: cucumber123
    #connection pool설정
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: cupool
#mvc패턴으로 jsp페이지 연결하기
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
        
#jpa환경설정하기
  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle9iDialect
    hibernate: 
      ddl-auto: update
      use-new-id-generator-mappings: true
      
    properties:
      hibernate:
        format_sql: true  

logging:
  level:
    root: info
    '[org.hibernate.type.descriptor.sql]': trace
    com.cu.cum: debug
    
    
    